services:
  tea_db_pg16:
    image: "postgres:16.2"
    restart: unless-stopped
    container_name: tea_postgres
    env_file:
      - database.env
    ports:
      - "55435:5432"
    volumes:
      - ${TEA_VOLUME_PATH}/tea_db_pg16/:/var/lib/postgresql/data/ 

  tea_backend:
    image: amazoncorretto:21-alpine
    restart: unless-stopped
    env_file:
      - database.env
    depends_on:
      - "tea_db_pg16"
    volumes:
      - ${EXEC_FILES}/:/opt/tea/
      - ${TEA_VOLUME_PATH}/:/var/tea/
    working_dir: /opt/tea
    command: java --enable-preview -Dspring.profiles.active=prod -jar tea-1.0.0.jar
    network_mode: host
    container_name: tea_backend

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - ${EXEC_FILES}/logs:/app/logs           # Accesso ai log della tua app
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml  # Config custom
      - /var/lib/promtail:/tmp                # File posizioni lettura log
    command: -config.file=/etc/promtail/promtail.yaml
